// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMidasAPI.Data;

#nullable disable

namespace ProjetoMidasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621173354_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("cnpjEmpresa")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("emailEmpresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("idResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneEmp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            IdEmpresa = 1,
                            cnpjEmpresa = "12345678901234",
                            emailEmpresa = "empresa@teste.com",
                            idResponsavel = 1,
                            nomeFantasia = "Teste",
                            razaoSocial = "Empresa Teste",
                            telefoneEmp = "123456789"
                        });
                });

            modelBuilder.Entity("Emprestimo", b =>
                {
                    b.Property<int>("IdSimEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSimEmprestimo"));

                    b.Property<int?>("CategoriaGasto")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacaoSE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IOFemprestimo")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("descricaoEmprestimo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("despesasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomeEmprestimo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("parcelasEmprestimo")
                        .HasColumnType("int");

                    b.Property<string>("provedorEmprestimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tarifasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorParcelas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSimEmprestimo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Emprestimos", (string)null);
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<int?>("CategoriaGasto")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoLancamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FrequenciaRecorrencia")
                        .HasColumnType("int");

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("IdRecorrencia")
                        .HasColumnType("int");

                    b.Property<int?>("IdSimEmprestimo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("ModoRecorrenciaMensal")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDaOcorrencia")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoLancamento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OrigemLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("QtdeRecorrencia")
                        .HasColumnType("int");

                    b.Property<int?>("StatusTransacao")
                        .HasColumnType("int");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("TotalOcorrencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdLancamento");

                    b.HasIndex("IdRecorrencia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoMidasAPI.Models.Projecao", b =>
                {
                    b.Property<int>("IdProjecao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjecao"));

                    b.Property<int?>("CategoriaGasto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProjecao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Projecoes", (string)null);
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.Property<int>("IdRecorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecorrencia"));

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("TipoRecorrenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("dsRecorrencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("momentoCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("obRecorrencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("qtdeRecorrencia")
                        .HasColumnType("int");

                    b.HasKey("IdRecorrencia");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TipoRecorrenciaId");

                    b.ToTable("Recorrencias", (string)null);
                });

            modelBuilder.Entity("Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsavel"));

                    b.Property<string>("emailResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sobrenomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsaveis", (string)null);

                    b.HasData(
                        new
                        {
                            IdResponsavel = 1,
                            emailResponsavel = "joao.silva@teste.com",
                            nomeResponsavel = "João",
                            sobrenomeResponsavel = "Silva",
                            telefoneResponsavel = "987654321"
                        });
                });

            modelBuilder.Entity("TipoRecorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoRecorrencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mensal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Semanal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Anual",
                            PadraoSistema = true
                        });
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Visitante");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            IdEmpresa = 0,
                            PasswordHash = new byte[] { 29, 181, 226, 114, 108, 145, 2, 48, 230, 57, 135, 208, 93, 214, 254, 244, 25, 149, 3, 160, 243, 143, 73, 140, 3, 75, 78, 15, 197, 57, 228, 78, 181, 252, 65, 159, 177, 28, 251, 76, 199, 237, 228, 112, 112, 72, 63, 6, 159, 70, 44, 142, 13, 95, 23, 166, 134, 178, 193, 231, 101, 15, 72, 146 },
                            PasswordSalt = new byte[] { 7, 165, 143, 2, 60, 238, 255, 112, 189, 33, 100, 13, 62, 18, 186, 93, 251, 149, 206, 87, 46, 218, 186, 210, 3, 110, 242, 1, 119, 216, 197, 131, 95, 141, 85, 118, 101, 144, 38, 23, 251, 210, 109, 14, 66, 85, 12, 93, 107, 61, 131, 228, 26, 12, 203, 228, 64, 52, 160, 32, 73, 7, 117, 219, 40, 140, 82, 179, 224, 131, 199, 197, 56, 119, 35, 135, 31, 12, 11, 199, 91, 216, 44, 165, 164, 176, 169, 241, 119, 174, 21, 108, 238, 14, 135, 202, 63, 245, 26, 80, 188, 151, 113, 128, 11, 85, 101, 42, 61, 153, 0, 91, 209, 237, 177, 118, 47, 225, 155, 94, 250, 10, 120, 70, 120, 120, 230, 155 },
                            Perfil = "Administrador",
                            TipoUsuario = 7,
                            emailUsuario = "",
                            nomeUsuario = "Admin",
                            sobrenome = "",
                            telefone = ""
                        });
                });

            modelBuilder.Entity("Emprestimo", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Emprestimos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.HasOne("Recorrencia", "Recorrencia")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdRecorrencia");

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoMidasAPI.Models.Projecao", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Projecoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Recorrencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipoRecorrencia", "TipoRecorrencia")
                        .WithMany()
                        .HasForeignKey("TipoRecorrenciaId");

                    b.Navigation("TipoRecorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Emprestimos");

                    b.Navigation("Lancamentos");

                    b.Navigation("Projecoes");

                    b.Navigation("Recorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
